### ISSUE TITLE
Questions about your westend/rococo bootnodes

### ISSUE THREAD

**Issue by bkchr** [stakeworld/system-parachain-collators#1]
Hey, I know that this isn't the right repo for this question, but I also don't know where to ask otherwise :P Do you run your bootnodes with `--block-pruning` enabled?

**Comment by stakeworld** [comment]
Hi @bkchr, I have moved my bootnodes recently and had them temporarily on a block pruned node, but I noticed that wasn't a good idea since a fresh node couldn't connect and get the first blocks. So I moved the polkadot and kusama bootnodes to a non block-pruned node, I think the westend boot node is still block pruned, I will fix that today. 

If you want i'm also reachable on element [@stakeworld.matrix.org](https://app.element.io/#/user%2F%40stakeworld%3Amatrix.org) or info@stakeworld.io

To be sure; `--state-pruning` is ok or do boot nodes have to be archive nodes?

**Comment by bkchr** [comment]
No state pruning is fine! Ty for the answer!
